## Run rabbitmq by docker
# docker run -d --hostname my-rabbit --name rabbitmq -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=quangduong -e RABBITMQ_DEFAULT_PASS=292003 -v rabbitmq:/var/lib/rabbitmq rabbitmq:3.12.2-management-alpine

spring:
  application:
    name: notification-service
  profiles:
    active: default
  config:
    import: configserver:http://service:password@localhost:8071
