version: '3.8'

services:
  nginx:
    image: nginx:alpine3.18
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      test-service:
        condition: service_started
    networks:
      - nginx-network
  test-service:
    build: ./test
    container_name: test-service
    ports:
      - "8080:8080"
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge
