version: '3.8'

services:
  #  zookeeper:
  #    image: wurstmeister/zookeeper
  #    container_name: zookeeper
  #    ports:
  #      - "2181:2181"
  #    volumes:
  #      - /data/zookeeper:/opt/zookeeper*
  #    networks:
  #      - kafka-network
  #  kafka:
  #    image: wurstmeister/kafka:2.13-2.8.1
  #    container_name: kafka
  #    ports:
  #      - "9092:9092"
  #    environment:
  #      KAFKA_ADVERTISED_HOST_NAME: localhost
  #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  ##      KAFKA_CREATE_TOPICS: "quickstart:1:1"
  #    depends_on:
  #      - zookeeper
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock
  #      - /data/kafka:/kafka
  #    networks:
  #      - kafka-network
  #networks:
  #  kafka-network:
  #    driver: bridge
  rabbitmq:
    image: rabbitmq:3.12.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: quangduong
      RABBITMQ_DEFAULT_PASS: 292003
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - my-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 292003
      MYSQL_USER: quangduong
      MYSQL_PASSWORD: 292003
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS order_service; CREATE DATABASE IF NOT EXISTS inventory_service;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - my-network
  eventuate-cdc:
    image: eventuateio/eventuate-cdc-service:0.16.0.RELEASE
    container_name: eventuate-cdc-service
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      EVENTUATE_CDC_READER_READER1_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:mysql://mysql:3306/order_service
      EVENTUATE_CDC_READER_READER1_MONITORINGSCHEMA: eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: root
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: 292003
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/order_service
      EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTUNIQUEID: 1
      EVENTUATE_CDC_READER_READER1_OFFSETSTOREKEY: MySqlBinlogOrderService
      EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME: db.history.common
      EVENTUATE_CDC_READER_READER1_OUTBOXID: 1

      EVENTUATE_CDC_READER_READER2_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:mysql://mysql:3306/inventory_service
      EVENTUATE_CDC_READER_READER2_MONITORINGSCHEMA: inventory_service
      EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: root
      EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: 292003
      EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/inventory_service
      EVENTUATE_CDC_READER_READER2_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER2_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER2_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER2_MYSQLBINLOGCLIENTUNIQUEID: 2
      EVENTUATE_CDC_READER_READER2_OFFSETSTOREKEY: MySqlBinlogInventoryService
      EVENTUATE_CDC_READER_READER2_OFFSETSTORAGETOPICNAME: db.history.common
      EVENTUATE_CDC_READER_READER2_OUTBOXID: 2

      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA: eventuate

      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader2
      EVENTUATE_CDC_PIPELINE_PIPELINE2_EVENTUATEDATABASESCHEMA: eventuate

      SPRING_PROFILES_ACTIVE: RabbitMQ
      RABBITMQ_URL: rabbitmq
volumes:
  rabbitmq:
  mysql:
networks:
  my-network:
    driver: bridge
