server:
  port: 8087

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:password@localhost:8761/eureka
#  instance:
#    hostname: localhost

spring:
  application:
    name: order-orchestrator-service
  cloud:
    function: handleCreateOrder
    stream:
      bindings:
        handleCreateOrder-in-0:
          destination: create-order-topic
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          replication-factor: 1
