spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: quangduong
    password: 292003
  profiles:
    active: default
  config:
    import: configserver:http://service:password@localhost:8071
