server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:order_service}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:292003}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
