server:
  port: 8086

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:password@localhost:8761/eureka
#  instance:
#    hostname: localhost

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:order_service}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:292003}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    function: handleUpdateOrder
    stream:
      bindings:
        handleUpdateOrder-in-0:
          destination: update-order-topic
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          replication-factor: 1
