server:
  port: 8761

spring:
  security:
    user:
      name: eureka
      password: password

eureka:
  instance:
    hostname: localhost
  client:
    # telling the built-in Eureka Client not to register with itself because our application should be acting as a server.
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
