server:
  port: 8761

spring:
  application:
    name:
      discovery-server
  security:
    user:
      name: eureka
      password: password

eureka:
  instance:
    hostname: localhost
  client:
    # client will not try to connect with eureka on start
    register-with-eureka: false
    # client will not fetch client list from server and use local cache to connect with other client
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
