#http://localhost:8071/auth-service/default
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:user_service}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:292003}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
