server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: quangduong
    password: 292003
  cloud:
    function:
    #      definition: sendMessage;convertToUpperCase;receiveMessage
    definition: handleMessage
    stream:
      bindings:
        #        sendMessage-out-0:
        #          destination: messages-topic
        #        convertToUppercase-in-0:
        #          destination: messages-topic
        #        convertToUppercase-out-0:
        #          destination: values-topic
        #        receiveMessage-in-0:
        #          destination: values-topic
        handleMessage-in-0:
          destination: notification-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
